package com.example.afuktju.solutionapp.greendao.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.afuktju.solutionapp.greendao.model.DtbPost;

import com.example.afuktju.solutionapp.greendao.model.DtbPostDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dtbPostDaoConfig;

    private final DtbPostDao dtbPostDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dtbPostDaoConfig = daoConfigMap.get(DtbPostDao.class).clone();
        dtbPostDaoConfig.initIdentityScope(type);

        dtbPostDao = new DtbPostDao(dtbPostDaoConfig, this);

        registerDao(DtbPost.class, dtbPostDao);
    }
    
    public void clear() {
        dtbPostDaoConfig.getIdentityScope().clear();
    }

    public DtbPostDao getDtbPostDao() {
        return dtbPostDao;
    }

}
